### ISSUE TITLE
Mainloop select() error: Success

### ISSUE THREAD

**Issue by LewisSpring** [pikvm/ustreamer#111]
Hi there! If I run
`./ustreamer --host=0.0.0.0 --port=8080 --device=/dev/video0`
I get "NO SIGNAL" through the feed.
[console.txt](https://github.com/pikvm/ustreamer/files/6448131/console.txt)
[v4l2.txt](https://github.com/pikvm/ustreamer/files/6448132/v4l2.txt)
Sorry about the TXT files, but Github decided to have a field day with the markdown/formatting if I just pasted the contents of the files and put them inside code characters

If I can provide anything more, please let me know.

**Comment by LewisSpring** [comment]
Using this [issue](https://github.com/pikvm/ustreamer/issues/52), I've seemed to fix it.
Of course, new issue, I can't go above 800*480
Thanks!

**Comment by LewisSpring** [comment]
Fixed that too by using --format=mjpeg.
Thanks!

**Comment by mdevaev** [comment]
:)

**Comment by erjoalgo** [comment]
Adding the `--format=MJPEG` fixed the issue for me. It wasn't obvious because the same exact command appeared to work fine outside the context of a system service, I assume there must have been a difference in the environment.

It would be very helpful if the error message could be updated to something more user-friendly, like "unable to determine stream format".
